# Generated by Django 4.2.6 on 2023-11-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Número')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('price', models.IntegerField()),
                ('ammount', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupado', 'Ocupado'), ('Deshabilitada', 'Deshabilitada')], default='Disponible', max_length=15, verbose_name='Estado')),
            ],
        ),
    ]
