# Generated by Django 4.2.6 on 2023-11-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Solicitada', 'Solicitada'), ('Aprobada', 'Aprobada'), ('Desaprobada', 'Desaprobada')], default='Solicitada', max_length=15),
        ),
    ]
