# Generated by Django 4.2.6 on 2023-11-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_userprofilegroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Solicitada', 'Solicitada'), ('Aprobada', 'Aprobada'), ('Desaprobada', 'Desaprobada'), ('Cancelada', 'Cancelada')], default='Solicitada', max_length=15),
        ),
    ]
